name: Flatpak Build

on:
  push:
    branches: 
      - master
      # TODO: remove
      - flatpak
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Flatpak bundle
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: overlayed.flatpak
          manifest-path: distribution/dev.overlayed.Overlayed.yaml
          cache-key: flatpak-builder-${{ github.ref }}
