
name: "Testing"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: "ubuntu-latest"
    steps:
      - name: test file
        run: |
          echo "1" > test.txt
      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: test.txt
          destination-dir: canary-test/
          multipart-size: 100
          max-retries: 3
          multipart-concurrent: true
